version: "3.9"

services:
  db:
    image: mysql:latest
    restart: always
    networks:
      - wpnet
    ports:
      - 3306:3306
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_USER: goldenowl
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    depends_on:
      - db
    networks:
      - wpnet
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_USER: goldenowl
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

  wordpress:
    image: wordpress:latest
    restart: always
    depends_on:
      - db
    networks:
      - wpnet
    ports:
      - 8080:80
    volumes:
      - ./wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: goldenowl
      WORDPRESS_DB_PASSWORD: password

networks:
  wpnet:
